S = input()
S = S.replace("c=", "_")
S = S.replace("c-", "_")
S = S.replace("dz=", "_")
S = S.replace("d-", "_")
S = S.replace("lj", "_")
S = S.replace("nj", "_")
S = S.replace("s=", "_")
S = S.replace("z=", "_")
print(len(S))